import LinearAlgebraPurePython as la 


print()
la.print_matrix(la.zeros_matrix(3,3))
print()
ID = la.identity_matrix(4)
la.print_matrix(ID)
print()
A = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
la.print_matrix(A)
print()
AM = la.copy_matrix(A)
la.print_matrix(AM)
print()
AT = la.transpose(A)
la.print_matrix(AT)
print()
C = la.matrix_addition(A,AT)
la.print_matrix(C)
print()
D = la.matrix_subtraction(C, AT)
la.print_matrix(D)
print()
AID = la.matrix_multiply(A, ID)
la.print_matrix(AID)
print()
MatrixList = [A, AT, ID]
Prod3 = la.multiply_matrices(MatrixList)
la.print_matrix(Prod3)
print()
ATA = la.transpose(la.transpose(A))
check = la.check_matrix_equality(A,ATA)
print("A = transpose of transpose of A?", check)
print()
AdotA = la.dot_product(A, A)
print("A.A =", AdotA)
print()
Vector = [[4],[4],[4]]
unitVector = la.unitize_vector(Vector)
la.print_matrix(unitVector)
print() 
